{
  "language": "python",
  "os": [
    "linux"
  ],
  "dist": "xenial",
  "python": [
    "3.9",
    "3.0"
  ],
  "install": [
    "pip install -r requiremnets.txt"
  ],
  "script": [
    "flake8"
  ]
}