language: python
dist: xenial
sudo: true
python:
  - 3.7
  - 3.8
  - 3.9
install:
  - pip install -r requirements.txt codecov
script:
  - flake8
  - pytest fusionaskatest --cov=fusionaskatest
after_success:
  - codecov